version: "3"
services:
  app:
    container_name: express-node-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example