version: "3"
services:
  app:
    build:
      context: .
      args:
      - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm start

# command:
  # docker-compose -f docker-compose.yml -f docker-compose.prod-yml up -d --build