version: "3"
services:
  app:
    build:
      context: .
      args:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev


# command:
  # docker-compose -f docker-compose.yml -f docker-compose.env-yml up -d --build